version: '3'

services:

     db:
        image: mysql:8.0.17
        environment:
           MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
           MYSQL_USER: 'user'
      # You can use whatever password you like
           MYSQL_PASSWORD: 'pass'
      # Password for root access
           MYSQL_ROOT_PASSWORD: 'password'
        volumes:
           - ./mydb:/var/lib/mysql
        ports:
           - "3306:3306"
     admin:
        image: adminer
        ports:
           - "8080:8080"
